### ISSUE TITLE
Unknown revision or path to karma-v0.10

### ISSUE THREAD

**Issue by jayrmotta** [yearofmoo-articles/AngularJS-Testing-Article#12]
After cloning the project and trying to run `npm install` I get:

```
[jayrmotta] ~/Development/AngularJS-Testing-Article (master) $ npm install
npm http GET https://registry.npmjs.org/grunt-css
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-contrib-connect
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-concat
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-shell
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http GET https://registry.npmjs.org/karma-mocha
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/karma-safari-launcher
npm http GET https://registry.npmjs.org/karma-firefox-launcher
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/karma-ng-scenario
npm http GET https://registry.npmjs.org/chai/1.4.0
npm http 304 https://registry.npmjs.org/grunt
npm http 304 https://registry.npmjs.org/grunt-css
npm http 304 https://registry.npmjs.org/grunt-contrib-connect
npm http 304 https://registry.npmjs.org/grunt-contrib-watch
npm http 304 https://registry.npmjs.org/grunt-shell
npm http 304 https://registry.npmjs.org/grunt-contrib-uglify
npm http 304 https://registry.npmjs.org/grunt-contrib-concat
npm http 304 https://registry.npmjs.org/karma-mocha
npm http 304 https://registry.npmjs.org/grunt-contrib-copy
npm http 304 https://registry.npmjs.org/karma-chrome-launcher
npm http 304 https://registry.npmjs.org/karma-safari-launcher
npm WARN package.json karma-safari-launcher@0.0.3 No README.md file found!
npm http 304 https://registry.npmjs.org/karma-firefox-launcher
npm http 304 https://registry.npmjs.org/karma
npm http 304 https://registry.npmjs.org/karma-ng-scenario
npm http 304 https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/chai/1.4.0
npm ERR! Failed resolving git HEAD (git://github.com/karma-runner/grunt-karma.git) fatal: ambiguous argument 'karma-v0.10': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (git://github.com/karma-runner/grunt-karma.git) Use '--' to separate paths from revisions
npm ERR! Failed resolving git HEAD (git://github.com/karma-runner/grunt-karma.git) 
npm ERR! Error: `git "rev-list" "-n1" "karma-v0.10"` failed with 128
npm ERR!     at ChildProcess.<anonymous> (/usr/local/Cellar/node/0.8.20/lib/node_modules/npm/lib/utils/exec.js:56:20)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:99:17)
npm ERR!     at maybeClose (child_process.js:638:16)
npm ERR!     at Socket.ChildProcess.spawn.stdin (child_process.js:815:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:96:17)
npm ERR!     at Socket._destroy.destroyed (net.js:358:10)
npm ERR!     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.4.0
npm ERR! command "/usr/local/Cellar/node/0.8.20/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/jayrmotta/Development/AngularJS-Testing-Article
npm ERR! node -v v0.8.20
npm ERR! npm -v 1.2.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jayrmotta/Development/AngularJS-Testing-Article/npm-debug.log
npm ERR! not ok code 0
```

It seems that the syntax for git repositories used on the package.json is not correct or I'm using some binaries in different versions. Anything comes to mind?

**Comment by jayrmotta** [comment]
```
[jayrmotta] ~/Development/AngularJS-Testing-Article (master) $ git diff
diff --git a/package.json b/package.json
index 88e25c3..f75fda3 100644
--- a/package.json
+++ b/package.json
@@ -15,7 +15,7 @@
     "grunt-contrib-watch": "~0.4.4",
     "grunt-shell": "~0.2.2",
     "grunt-contrib-copy": "~0.4.1",
-    "grunt-karma": "git://github.com/karma-runner/grunt-karma.git#karma-v0.10",
+    "grunt-karma": "git://github.com/karma-runner/grunt-karma.git#0.4.5",
     "bower": "~0.9.2",
     "karma": "~0.9.5",
     "karma-mocha": "latest",
```

This made the app works for me! :)

**Comment by christrees** [comment]
I also this 'discovered' this with Issue #14 ... and forgot search the issues ;-) sorry...
