### ISSUE TITLE
requiring karma-shared.conf throws an error

### ISSUE THREAD

**Issue by jayrmotta** [yearofmoo-articles/AngularJS-Testing-Article#13]
I have just cloned the repository and run `npm install && bower install`, everything looks fine except when I try to run:

```
[jayrmotta] ~/Development/AngularJS-Testing-Article (master) $ grunt autotest:e2e
Running "karma:e2e_auto" (karma) task
[2013-07-31 01:45:15.608] [ERROR] config - Invalid config file!
 { [Error: Cannot find module './karma-shared.conf'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module './karma-shared.conf'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at evalmachine.<anonymous>:1:14
    at readConfigFile (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt-karma/node_modules/karma/lib/config.js:158:8)
    at Object.parseConfig (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt-karma/node_modules/karma/lib/config.js:177:58)
    at Object.exports.start (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt-karma/node_modules/karma/lib/server.js:19:20)
    at Object.module.exports (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt-karma/tasks/grunt-karma.js:40:14)
    at Object.task.registerMultiTask.thisTask (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/grunt/task.js:258:15)
    at Object.task.registerTask.thisTask.fn (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.Task.start._running (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/util/task.js:235:24)
    at Task.<anonymous> (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/util/task.js:215:7)
    at Task.runTaskFn (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/util/task.js:238:9)
    at Task.<anonymous> (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/util/task.js:281:12)
    at Task.start (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/util/task.js:290:5)
    at Object.grunt.tasks (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/grunt.js:155:8)
    at Object.module.exports [as cli] (/Users/jayrmotta/Development/AngularJS-Testing-Article/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/grunt-cli/bin/grunt:36:20)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

what am I doing wrong?

**Comment by ds82** [comment]
Same problem here. I was able to fix it by installing a newer grunt-karma version / adjusting package.json:
-    "grunt-karma": "git://github.com/karma-runner/grunt-karma.git#karma-v0.10",
-    "grunt-karma": "~0.6.1",

.. the tests don't run tough ... ;)

**Comment by redrick** [comment]
I had to replace these two lines in package.json:

```
"grunt-karma": "git://github.com/karma-runner/grunt-karma.git#0.4.5",
"karma": "~0.9.5",
```

with these two (like @ds82 suggested + one dependency ):

```
"grunt-karma": "~0.6.1",   
"karma": "~0.10.0",
```

and now test and all are running, but oh my god they are failing :(

UPDATE: here I forked and corrected, not creating pull request caause its not that big a deal, but have a look if you want :)

```
https://github.com/redrick/AngularJS-Testing-Article/commit/b4a02926c43bca8a3d1b4d58feacc939f8a1e873
```
