### ISSUE TITLE
server.sh doesn't work

### ISSUE THREAD

**Issue by hokster7** [yearofmoo-articles/AngularJS-Testing-Article#2]
```
[WARN] No ENV file found
[OKAY] Trimming display Output to 54 Columns
14:33:23 e2e_server.1 |  Http Server running at http://localhost:8100/
14:33:23 web_server.1 |  events.js:68
14:33:23 web_server.1 |  throw arguments[1]; // Unhandled 'error' event
14:33:23 web_server.1 |  ^
14:33:23 web_server.1 |  Error: listen EADDRINUSE
14:33:23 web_server.1 |  at errnoException (net.js:769:11)
14:33:23 web_server.1 |  at Server._listen2 (net.js:909:14)
14:33:23 web_server.1 |  at listen (net.js:936:10)
14:33:23 web_server.1 |  at Server.listen (net.js:993:9)
14:33:23 web_server.1 |  at dns.js:71:18
14:33:23 web_server.1 |  at process.startup.processNextTick.process._tickCa…
[DONE] Killing All Processes
14:33:23 web_server.1 Exited Abnormally
14:33:23 e2e_server.1 Exited Abnormally
```

**Comment by swallentin** [comment]
From what I can read you're already running a web server on the port number, 8100. This is causes the script to fail, see the EADDRINUSE error message.
Close down the other service that is blocking the port number for some swag!

**Comment by matsko** [comment]
The node foreman tool doesn't seem to be working well and the old HTTP server provided in angular-seed is outdated. So I'll switch it over to use grunt and swap node foreman for something else and this should fix this.

**Comment by eddiemonge** [comment]
I have the same issue with nothing else running on port 8100.

**Comment by matsko** [comment]
I will replace this to use Grunt and an alternative Proc manager as well as update the article to use karma over the weekend.
