### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Gargaroz** [yearofmoo-articles/AngularJS-Testing-Article#44]
Hi, I tried to run npm install after cloning this repository via the steps explained in the blog post, but when I run `npm install` in a ashell with Admin perms I get the following error:

```
bower bootstrap.css#2.1.1                      error Path must be a string. Received [ 'C:\\Users\\GESPOS~1\\AppData\\Local\\Temp\\AD-gesposito\\bower\\bootstrap.css-5656-KvvBEk',   [Function: _cleanupCallback] ]

Stack trace:
TypeError: Path must be a string. Received [ 'C:\\Users\\GESPOS~1\\AppData\\Local\\Temp\\AD-gesposito\\bower\\bootstrap.css-5656-KvvBEk',
  [Function: _cleanupCallback] ]
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at GitHubResolver.GitResolver._cleanup (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\core\resolvers\GitResolver.js:185:26)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\core\resolvers\GitResolver.js:74:25
    at Promise.apply (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:1122:26)
    at Promise.promise.promiseDispatch (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:752:41)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:1337:14
    at flush (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

Console trace:
Trace
    at StandardRenderer.error (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\renderers\StandardRenderer.js:74:17)
    at Logger.<anonymous> (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\bin\bower:109:18)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\commands\install.js:27:16
    at _rejected (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:808:24)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:834:30
    at Promise.when (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:1079:31)
    at Promise.promise.promiseDispatch (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:752:41)

System info:
Bower version: 1.2.8
Node version: 4.4.2
OS: Windows_NT 10.0.10586 x64

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.2.1
npm WARN karma-mocha@0.2.2 requires a peer of mocha@* but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-requirejs@~0.2.0 but none was installed.
npm WARN yom-angularjs-testing-article@0.0.0 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gesposito\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! yom-angularjs-testing-article@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yom-angularjs-testing-article@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yom-angularjs-testing-article package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yom-angularjs-testing-article
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yom-angularjs-testing-article
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\npm-debug.log
```

What am I possibly doing wrong?

**Comment by Gargaroz** [comment]
[As suggested by this comment](http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-karma.html#comment-1540097603) I deleted the AngularJS-Testing-Article directory with all its content, then cloned it again via `git clone git://github.com/yearofmoo-articles/AngularJS-Testing-Article.git` but I still get a similar error:

```
bower components-font-awesome#3.1.0            error Path must be a string. Received [ 'C:\\Users\\GESPOS~1\\AppData\\Local\\Temp\\AD-gesposito\\bower\\components-font-awesome-8452-05rioF',   [Function: _cleanupCallback] ]

Stack trace:
TypeError: Path must be a string. Received [ 'C:\\Users\\GESPOS~1\\AppData\\Local\\Temp\\AD-gesposito\\bower\\components-font-awesome-8452-05rioF',
  [Function: _cleanupCallback] ]
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at GitHubResolver.GitResolver._cleanup (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\core\resolvers\GitResolver.js:185:26)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\core\resolvers\GitResolver.js:74:25
    at Promise.apply (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:1122:26)
    at Promise.promise.promiseDispatch (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:752:41)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:1337:14
    at flush (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

Console trace:
Trace
    at StandardRenderer.error (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\renderers\StandardRenderer.js:74:17)
    at Logger.<anonymous> (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\bin\bower:109:18)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\bower\lib\commands\install.js:27:16
    at _rejected (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:808:24)
    at C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:834:30
    at Promise.when (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:1079:31)
    at Promise.promise.promiseDispatch (C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\node_modules\q\q.js:752:41)

System info:
Bower version: 1.2.8
Node version: 4.4.2
OS: Windows_NT 10.0.10586 x64

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.2.1
npm WARN karma-mocha@0.2.2 requires a peer of mocha@* but none was installed.
npm WARN karma@0.10.10 requires a peer of karma-requirejs@~0.2.0 but none was installed.
npm WARN yom-angularjs-testing-article@0.0.0 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gesposito\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.2
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! yom-angularjs-testing-article@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yom-angularjs-testing-article@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yom-angularjs-testing-article package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yom-angularjs-testing-article
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yom-angularjs-testing-article
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\gesposito\Documents\GitHub\AngularJS-Testing-Article\npm-debug.log
```

Should I ignore this or it's a blocking error and there's an actual way to fix it?

**Comment by aaronjenson** [comment]
Pull request #43 contains some fixes that worked for me to fix that error.
